name=M5Unit-THERMO
version=0.3.1
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack UNIT THERMO using M5UnitUnified
paragraph=Supports MLX90614 IR thermometer (UnitNCIR, SKU:U028), NCIR2 (SKU:U150), and MLX90640 thermal camera (UnitThermal2, SKU:U149).
category=Device Control
url=https://github.com/m5stack/M5Unit-THERMO
architectures=esp32
includes=M5UnitUnifiedTHERMO.h
depends=M5UnitUnified,M5Utility,M5HAL
