;-----------------------------------------------------------------------
; For NCIR2
;-----------------------------------------------------------------------

[env:test_UnitNCIR2_Core]
extends=Core, option_release, arduino_latest
lib_deps = ${Core.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_Core2]
extends=Core2, option_release, arduino_latest
lib_deps = ${Core2.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_CoreS3]
extends=CoreS3, option_release, arduino_latest
lib_deps = ${CoreS3.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_Fire]
extends=Fire, option_release, arduino_latest
lib_deps = ${Fire.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_StampS3]
extends=StampS3, option_release, arduino_latest
lib_deps = ${StampS3.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_Dial]
extends=Dial, option_release, arduino_latest
lib_deps = ${Dial.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_Atom]
extends=Atom, option_release, arduino_latest
lib_deps = ${Atom.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_AtomS3]
extends=AtomS3, option_release, arduino_latest
lib_deps = ${AtomS3.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_AtomS3R]
extends=AtomS3R, option_release, arduino_latest
lib_deps = ${AtomS3R.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_NanoC6]
extends=NanoC6, option_release, nanoc6_latest
lib_deps = ${NanoC6.lib_deps}
  ${test_fw.lib_deps} 
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_StickCPlus]
extends=StickCPlus, option_release, arduino_latest
lib_deps = ${StickCPlus.lib_deps} 
  ${test_fw.lib_deps} 
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_StickCPlus2]
extends=StickCPlus2, option_release, arduino_latest
lib_deps = ${StickCPlus2.lib_deps} 
  ${test_fw.lib_deps} 
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_Paper]
extends=Paper, option_release, arduino_latest
lib_deps = ${Paper.lib_deps} 
  ${test_fw.lib_deps} 
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_CoreInk]
extends=CoreInk, option_release, arduino_latest
lib_deps = ${CoreInk.lib_deps} 
  ${test_fw.lib_deps} 
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_StickS3]
extends=StickS3, option_release, arduino_latest
build_flags = ${StickS3.build_flags}
  ${option_release.build_flags}
lib_deps = ${StickS3.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_Cardputer]
extends=Cardputer, option_release, arduino_latest
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
lib_deps = ${Cardputer.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_Tab5]
extends=Tab5, option_release, pioarduino_latest
build_flags = ${Tab5.build_flags}
  ${option_release.build_flags}
lib_deps = ${Tab5.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:test_UnitNCIR2_NessoN1]
extends=NessoN1, option_release, pioarduino_latest
lib_deps = ${NessoN1.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_ncir2

[env:UnitNCIR2_PlotToSerial_Core_Arduino_latest]
extends=Core, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_Core2_Arduino_latest]
extends=Core2, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_CoreS3_Arduino_latest]
extends=CoreS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_StampS3_Arduino_latest]
extends=StampS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_Atom_Arduino_latest]
extends=Atom, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_AtomS3_Arduino_latest]
extends=AtomS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_AtomS3R_Arduino_latest]
extends=AtomS3R, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_Dial_Arduino_latest]
extends=Dial, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_StickCPlus_Arduino_latest]
extends=StickCPlus, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_StickCPlus2_Arduino_latest]
extends=StickCPlus2, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_Paper_Arduino_latest]
extends=Paper, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_CoreInk_Arduino_latest]
extends=CoreInk, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_Fire_Arduino_latest]
extends=Fire, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>

[env:UnitNCIR2_PlotToSerial_StickS3_Arduino_latest]
extends=StickS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>
build_flags = ${StickS3.build_flags}
  ${option_release.build_flags}

[env:UnitNCIR2_PlotToSerial_Cardputer_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}

[env:UnitNCIR2_PlotToSerial_Tab5_Arduino_latest]
extends=Tab5, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>
build_flags = ${Tab5.build_flags}
  ${option_release.build_flags}

[env:UnitNCIR2_PlotToSerial_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/PlotToSerial>


;
; For the following samples, please refer to PlotToSerial to create env for your own environment
; 以下のサンプルは、PlotToSerial を参考にして、自分の環境にあった env を作成してください
;
; SimpleDisplay
[env:UnitNCIR2_SimpleDisplay_Core_Arduino_latest]
extends=Core, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitNCIR2/SimpleDisplay>

